In [1]:
import numpy as np

In [4]:
x=np.array([10.5,5.2,3.25])

In [5]:
x.shape

(3,)

In [16]:
i=2
x[i]

3.25

In [18]:
np.expand_dims(x,axis=1).shape

(3, 1)

In [20]:
np.expand_dims(x,axis=1)

array([[10.5 ],
       [ 5.2 ],
       [ 3.25]])

In [21]:
A=np.array([
    [10,20,30],
    [40,50,60]])

In [22]:
A

array([[10, 20, 30],
       [40, 50, 60]])

In [23]:
A.shape

(2, 3)

In [24]:
i=0
j=2
A[i,j]

30

In [25]:
#column vector
j=1
A[:,j]

array([20, 50])

In [45]:
#row vector
i=1
A[i,:]

array([40, 50, 60])

In [30]:
#행렬의 곱셉

In [33]:
import numpy as np
x=np.array([1,2,3])
y=np.array([4,5,6])
x.dot(y),y.dot(x)

(32, 32)

In [73]:
x=np.array([1,2,3])
y=np.array([4,5,6,8,10])
x=np.expand_dims(x,axis=1)
y=np.expand_dims(y,axis=0)
x.dot(y)

array([[ 4,  5,  6,  8, 10],
       [ 8, 10, 12, 16, 20],
       [12, 15, 18, 24, 30]])

In [49]:
np.matmul(x,y)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [50]:
#외적이 유용한 경우, A의 행렬은 모두 동일한 벡터x를 가지고 있음

In [51]:
#column vector
x=np.expand_dims(np.array([1,2,3]),axis=1)
x

array([[1],
       [2],
       [3]])

In [57]:
ones=np.ones([1,4])
ones

array([[1., 1., 1., 1.]])

In [60]:
A=np.matmul(x,ones)
A

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [61]:
#행렬과 벡터

In [62]:
A=np.array([
    [1,2,3],
    [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
ones=np.ones([3,1])
ones

array([[1.],
       [1.],
       [1.]])

In [69]:
x=np.matmul(A,ones)
x

array([[ 6.],
       [15.]])

In [70]:
#열 벡터를 오른쪽에 곱하고(Ax), A가 열의 형태로 표현되었을 떄

In [71]:
A=np.array([
    [1,0,1],
    [0,1,1]])
x=np.array([
    [1],
    [2],
    [3]])
np.matmul(A,x)

array([[4],
       [5]])

In [82]:
A=np.arange(1,7).reshape(2,3)

In [83]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [86]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [88]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [95]:
A=np.matrix([[2,1],[3,4]])
A.I

matrix([[ 0.8, -0.2],
        [-0.6,  0.4]])

In [96]:
np.diag([4,5,6])

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [97]:
D=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])
np.diag(D)

array([1, 5, 9])

In [98]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [99]:
A=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [101]:
B=np.array([[7,8],
           [10,11],
           [12,42]])
np.matmul(A,B).T

array([[ 63, 150, 237],
       [156, 339, 522]])

In [102]:
#대칭핼렬

In [103]:
np.matmul(A,A.T)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [104]:
np.matmul(A.T,A)

array([[ 66,  78,  90],
       [ 78,  93, 108],
       [ 90, 108, 126]])

In [105]:
#norm

In [106]:
import numpy.linalg as LA
LA.norm(np.array([3,4]))

5.0

In [107]:
A=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])
LA.norm(A)

16.881943016134134

In [110]:
np.trace(A.T.dot(A))**0.5

16.881943016134134

In [115]:
#rank 함수

In [111]:
A=np.array([
    [1,4,2],
    [2,1,-3],
    [3,5,-1]])


In [113]:
A[:,2] == -2*A[:,0] + A[:,1]

array([ True,  True,  True])

In [114]:
a=-2*A[:,0] + A[:,1]
a

array([ 2, -3, -1])

In [116]:
LA.matrix_rank(A)

2

In [117]:
# 역행렬

In [119]:
A=np.array([
    [1,2],
    [3,4]])
LA.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [120]:
LA.inv(LA.inv(A))

array([[1., 2.],
       [3., 4.]])

In [122]:
A=np.array([
    [1,2],
    [3,4]])

LA.det(A)

-2.0000000000000004

In [10]:
# 고유값과 고유벡터
import numpy as np
import numpy.linalg as LA
 
A=np.array([[1,2,3],
            [4,5,6],
            [7,8,0]])

In [4]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [14]:
LA.eig(A)

(array([12.12289378, -0.38838384, -5.73450994]),
 array([[-0.29982463, -0.74706733, -0.27625411],
        [-0.70747178,  0.65820192, -0.38842554],
        [-0.63999131, -0.09306254,  0.87909571]]))

In [17]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
A=np.arange(25).reshape(5,5)

In [29]:
A=np.array(A)

In [30]:
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
