## Numpy

### 1. Numpy Array and Operation

- numpy의 기본적인 사용법에 대해서 배워봅니다.


- numpy에서 numpy.array를 만드는 여러가지 방법과 지원하는 연산자에 대해서 공부합니다.

### 1.1. Numpy Array creation

In [ ]:
# numpy 라이브러리를 불러옵니다.
import numpy as np

In [ ]:
# 파이썬 리스트 선언
data = [1,2,3,4,5]
data

[1, 2, 3, 4, 5]

In [ ]:
# 파이썬 2차원 리스트(행렬) 선언
data2 = [[1,2],[3,4]]
data2

[[1, 2], [3, 4]]

In [ ]:
# 파이썬 list를 numpy array로 변환합니다.
arr= np.array(data)
# numpy array를 만드는 방식의 대부분은 파이썬 리스트를 np.array로 변환하는 방식입니다.
arr= np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
# 2차원 리스트를 np.array로 만듭니다.
arr2 = np.array(data2) # data2라는 리스트를 numpy array로 만들어라.
arr2 # 2차원 numpy array -> 행렬!

array([[1, 2],
       [3, 4]])

In [ ]:
# 0부터 9까지 숫자를 자동으로 생성한 array
print(np.array(list(range(10))))

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 10부터 99까지 숫자를 자동으로 생성한 array
print(np.arange(10,100))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [ ]:
arr.shape

(5,)

### 1.2. Reshaping array

In [ ]:
# 3 x 3 행렬을 만들어봅시다.
x = np.array([[1,2,3],[4,5,6],[ 7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# reshape을 이용하여 만들어봅시다.
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# row vector를 column vector로
np.arange(6).reshape(6,1)     #(6,0) != (6,1) / (6,0) : 1행 6열 , (6,1) : 6행 1열

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
# 펼치기
x.reshape(-1,)       #(9,) = (-1,)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 1.3. Concatenation of arrays

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# arr1 + arr2 = ?
print(arr1+arr2)
# arr1와 arr2를 합칩니다

print(np.concatenate([arr1,arr2]))

[5 7 9]
[1 2 3 4 5 6]


In [ ]:
# stacking vertically
np.vstack([arr1,arr2])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# stacking horizontally
np.hstack([arr1,arr2])

array([1, 2, 3, 4, 5, 6])

## 1.4. Array Arithmetic (like vector) --> Universal Function

In [ ]:
# v1 = (1, 2, 3), v2 = (4, 5, 6) 벡터 2개 생성하기.
v1= np.array([1,2,3])
v2= np.array([4,5,6])

In [ ]:
# 리스트로 더하기 연산해보기
L=[1,2,3,4]
L2=[5,6,7,8]
L+L2

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
#  vector addition
v1+v2

array([5, 7, 9])

In [ ]:
#  vector subtraction
v1-v2

array([-3, -3, -3])

In [ ]:
# (not vector operation) elementwise multiplication
v1*v2

array([ 4, 10, 18])

In [ ]:
# (not vector operation) elementwise division
v1/v2

array([0.25, 0.4 , 0.5 ])

In [ ]:
# dot product
v1 @ v2 # 1x4 + 2x5 + 3x6

32

### 1.5. Broadcast and Universal Function

- 서로 크기가 다른 numpy array를 연산할 때, 자동으로 연산을 전파(broadcast)해주는 기능. 행렬곱 연산을 할 때 편리하다.

In [ ]:
arr1 = np.array([1,2,3])

In [ ]:
arr2 = np.array([[-1,-1,-1],
                 [1,1,1]]) 
arr2.shape

(2, 3)

In [ ]:
# 2개의 array를 더해보면?
arr1 + arr2 # 2->2->3(v)

array([[0, 1, 2],
       [2, 3, 4]])

In [ ]:
# 2개의 array를 곱해보면? (**)
arr1 * arr2

array([[-1, -2, -3],
       [ 1,  2,  3]])

- Universal Function : broadcast 기능을 확장해서, numpy array의 모든 원소에 동일한 함수를 반복문으로 적용한 것과 같은 효과를 내는 기능.

In [ ]:
# f = lambda x : 1/x
f= lambda x: 1/x

for i in arr1:
  print(f(i))

1.0
0.5
0.3333333333333333


In [ ]:
# f = lambda x : x + 2
arr1 = arr+2
arr1

array([3, 4, 5, 6, 7])

### 1.6. Indexing
**numpy의 인덱싱은 list의 인덱싱과 동일하다**

In [ ]:
arr1 = np.arange(10)

In [ ]:
# 첫번째 원소
arr1[0]

0

In [ ]:
# 마지막 원소
arr1[-1]

9

In [ ]:
# 앞에서부터 원소 3개 slicing
arr1[:3]

array([0, 1, 2])

In [ ]:
arr2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
arr2.shape

(3, 4)

In [ ]:
# arr2의 2row, 3column 원소 = 7
arr2[1,2]

7

In [ ]:
# arr2의 세번째 column [3, 7, 11]
arr2[:,2]

array([ 3,  7, 11])

In [ ]:
# arr2의 두번째 row
arr2[: , 1]

array([ 2,  6, 10])

In [ ]:
#arr2의 1행1열 부터 2행 2열까지 추출하라
arr2[0:2,0:2]

array([[1, 2],
       [5, 6]])

## 2. Numpy Methods

- numpy에서 사용되는 여러가지 함수들을 사용해봅시다.

### 2.1. Math Functions 

In [ ]:
# 표준정규분포에서 random sampling을 한 원소를 가지는 5x3 행렬을 만든다.
mat1 = np.random.randn(5,4)
mat1

# -1 과 1 사이의 표준 정규분포를 뽑아준다.

array([[ 1.21190834, -0.24100569, -1.9970341 ,  0.77484442],
       [ 0.97804661, -1.7344566 , -0.44636269,  0.23814445],
       [-1.44011291, -0.33083116, -1.81824085,  1.73909674],
       [ 0.2213763 ,  0.80271216,  0.15460324, -0.40820313],
       [ 0.07928762, -0.35300587,  0.03773491,  0.93113391]])

In [ ]:
# mat1에 절대값 씌우기
np.abs(mat1)

array([[1.21190834, 0.24100569, 1.9970341 , 0.77484442],
       [0.97804661, 1.7344566 , 0.44636269, 0.23814445],
       [1.44011291, 0.33083116, 1.81824085, 1.73909674],
       [0.2213763 , 0.80271216, 0.15460324, 0.40820313],
       [0.07928762, 0.35300587, 0.03773491, 0.93113391]])

In [ ]:
# mat1 제곱하기
np.square(mat1)

array([[1.46872182e+00, 5.80837442e-02, 3.98814519e+00, 6.00383873e-01],
       [9.56575177e-01, 3.00833970e+00, 1.99239651e-01, 5.67127770e-02],
       [2.07392520e+00, 1.09449256e-01, 3.30599978e+00, 3.02445748e+00],
       [4.90074670e-02, 6.44346819e-01, 2.39021631e-02, 1.66629794e-01],
       [6.28652713e-03, 1.24613146e-01, 1.42392333e-03, 8.67010351e-01]])

In [ ]:
# mat1의 제곱근 구하기
np.sqrt(mat1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


array([[1.10086708,        nan,        nan, 0.88025247],
       [0.98896239,        nan,        nan, 0.48800046],
       [       nan,        nan,        nan, 1.31874817],
       [0.47050643, 0.89594205, 0.39319619,        nan],
       [0.28158058,        nan, 0.19425475, 0.9649528 ]])

In [ ]:
# linear algebra functions
vec = np.array([1,0,0])

# 1. norm
np.linalg.norm(vec)  #vector의 L2 norm

# 2. eigenvalue (벡터의 고유값)
mat = np.array([[1,2], [3,4]])
np.linalg.eig(mat)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

### 2.2. Aggregation functions 
**합계함수**

In [ ]:
mat2 = np.random.rand(3, 2)
mat2

# 0과 1사이에서 랜덤으로 추출

array([[0.63973863, 0.31395682],
       [0.88283695, 0.24936637],
       [0.6468587 , 0.7098764 ]])

In [ ]:
# Summation
np.sum(mat2)

np. sum(mat2, axis=0)  #axis=0 열을 기준
np.sum(mat2, axis=1)   #axis=1 행을 기준

array([0.95369545, 1.13220332, 1.3567351 ])

In [ ]:
# mean
np.mean(mat2, axis=0)

array([0.72314476, 0.42439987])

In [ ]:
# std
np.std(mat2)

0.22229175643954122

In [ ]:
# min, max
np.min(mat2, axis=0)
np.max(mat2, axis=1)

array([0.63973863, 0.88283695, 0.7098764 ])

In [ ]:
# 최소값이 있는 Index
np.argmin(mat2, axis=0)


array([0, 1])

In [ ]:
# 최대값이 있는 Index
np.argmax(mat2, axis=1)

array([0, 0, 1])

In [ ]:
# 그냥 정렬 (오름차순 정렬만 지원합니다)
np.sort(mat2)

# 만약 내림차순으로 하겠다면?
np.sort(mat2, axis=0)[::-1]

array([[0.88283695, 0.7098764 ],
       [0.6468587 , 0.31395682],
       [0.63973863, 0.24936637]])

In [ ]:
# index를 정렬
np.argsort(mat2, axis=0)

array([[0, 1],
       [2, 0],
       [1, 2]])

## 3. Performance Check

- Universal Function 기능을 통해 반복문을 사용한 것보다 훨씬 빠른 성능을 냅니다.


- 직접 실험을 통해 그 차이를 확인해보겠습니다.

In [ ]:
np.random.seed(0) #random에 대한 실행 결과를 고정

def reverse_num(values):
    output = np.empty(len(values))
    
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    
    return output

In [ ]:
# 1부터 100까지 범위에서 1000000개를 랜덤으로 뽑아서 array를 만듭니다.
big_array = np.random.randint(1,100,10000000000000)
big_array

In [ ]:
%timeit reverse_num(big_array)

2.48 s ± 525 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%timeit 1.0 / big_array

1.95 ms ± 74.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
